version: "3"
services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    command: redis-server --appendonly yes
    volumes:
      - ./data:/data
  app:
    image: kelshahawe/route-api
    depends_on:
      - redis
    expose:
      - "8080"
